### ISSUE TITLE
Suggest including (Announced) in product title, not as a tooltip on RHS icon

### ISSUE THREAD

**Issue by ndyck14** [matterdatabase/matterdatabase#1]
The tool tip for announced is an 'x' icon. This can be misleading or at least a bit confusing. I suggest that for announced but unreleased products, you put it right in the product name.

It may also be beneficial to distinguish between 
1. Products that have been announced but not released
2. Product upgrades that have been announced but not released

**Comment by matterdatabase** [comment]
Good point. I share your opinion that it is a bit confusing currently. My target is to fix this in the next update.

**Comment by matterdatabase** [comment]
As a new strategy, which will make it way more clear for everyone, I think it is best to only display currently available devices. I plan to remove the devices (display: false) for devices that are not available.

**Comment by Croydon** [comment]
What about a toggle that filters the results accordingly?

**Comment by matterdatabase** [comment]
I think for the average person, just a list of available devices is most useful and gets confusing quite quickly. And maintaining each existing device in the database for when it has switched from announced to available is quite some work.
